### ISSUE TITLE
Podman desktop automatic installation of Podman with space on user path fails

### ISSUE THREAD

**Issue by nikolaqm** [containers/podman-desktop#1208]
### Bug description

When user path has a space e.g. `C:\Users\John Doe`, when trying to install Podman on fresh Windows 10 installation, Podman installation fails raising error about path `C:\users\John` (note missing `Doe`). This is presumably space handling issue.

Downloading Podman installer manually and running it works fine.

### Operating system

Windows 10

### Version

0.10.0

### Steps to reproduce

1. Fresh Windows 10 Pro VM install, defining user name with a space e.g. `John Doe`
2. Download Podman desktop and start
3. Follow steps to enable Hyper V and WSL on fresh Windows install (2x restart)
4. Once no Podman system is identified by Podman Desktop, click on automatic install.

**Comment by benoitf** [comment]
Hello @nikolaqm this should have been fixed by https://github.com/containers/podman-desktop/issues/806

**Comment by nikolaqm** [comment]
@benoitf thank you I guess that will come that in next version then. And sorry for duplication, I missed that issue somehow.

**Comment by benoitf** [comment]
@nikolaqm well it should be included in 0.10.0 so maybe we need to keep the issue

Is it possible to try using a pre-release on your side ?
https://github.com/containers/podman-desktop/releases/tag/v0.0.202301191417-c92e09a

**Comment by nikolaqm** [comment]
@benoitf I tried with the latest pre-release (https://github.com/containers/podman-desktop/releases/tag/v0.0.202301201541-e822a56). I still receive error below for user `john doe` so it seems there is still some issue.

![image](https://user-images.githubusercontent.com/91256501/213762914-a894ccc1-515e-4e9a-8a51-924d7713ae50.png)

**Comment by nikolaqm** [comment]
Note difference to the #806 : there in error path was `C:\Users\Jeff` and here `C:\Users\john\`  
i.e. now it seems that `\` is inserted before space, but still executor parses command as if that's the end of string.
I would guess there are missing double quotes in the command somewhere.

**Comment by benoitf** [comment]
@nikolaqm could you check https://github.com/containers/podman-desktop/actions/runs/4017315906 by using an artifact produced by the ci ?
