### ISSUE TITLE
Podman Desktop unable to detect the Virtual Machine Platform already enabled

### ISSUE THREAD

**Issue by zikzakjack** [containers/podman-desktop#7414]
### Bug description

After uninstalling the older version, I am trying to set up Podman Desktop and Podman on my Windows Laptop. I keep getting the error below on the check requirements screen. 

`Virtual Machine Platform should be enabled to be able to run Podman.
`

### Operating system

Windows 11

### Installation Method

Installer from website/GitHub releases

### Version

1.10.2

### Steps to reproduce

https://github.com/containers/podman-desktop/discussions/7413

### Relevant log output

```shell
https://github.com/containers/podman-desktop/discussions/7413
```

### Additional context

https://github.com/containers/podman-desktop/discussions/7413

**Comment by bodzebod** [comment]
I have almost the same problem. I installed podman desktop for the first time, and it can't detect that I deployed the virtual machine feature.

**Comment by dgolovin** [comment]
@bodzebod could you run in powershell command below? What is the output?

`(Get-WmiObject -Query "Select * from Win32_OptionalFeature where InstallState = '1'").Name`

**Comment by bodzebod** [comment]
here it is:
![Image](https://github.com/user-attachments/assets/688c3515-3f43-45a1-b28a-8d8e04f40029)

For your information, I have posted more details in a similar ticket: https://github.com/containers/podman-desktop/discussions/7413#discussioncomment-11001835

**Comment by dgolovin** [comment]
@bodzebod would you do another test and run line below in powershell? It prints out you current encoding used in powershell.

```
[System.Console]::OutputEncoding
```

output should look alike to one below

```
PS C:\p\encoding-test> [System.Console]::OutputEncoding

IsSingleByte      : True
BodyName          : IBM437
EncodingName      : OEM United States
HeaderName        : IBM437
WebName           : IBM437
WindowsCodePage   : 1252
IsBrowserDisplay  : False
IsBrowserSave     : False
IsMailNewsDisplay : False
IsMailNewsSave    : False
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 437
```

Thank you!

**Comment by bodzebod** [comment]
Sure, here i is:

```
[System.Console]::OutputEncoding

IsSingleByte      : True
EncodingName      : Western European (DOS)
WebName           : ibm850
HeaderName        : ibm850
BodyName          : ibm850
Preamble          :
WindowsCodePage   :
IsBrowserDisplay  :
IsBrowserSave     :
IsMailNewsDisplay :
IsMailNewsSave    :
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : False
CodePage          : 850
```

**Comment by dgolovin** [comment]
I have tested this use case using code snippet below on Windows 10 and 11. The result is the same it prints out `VirtualMachinePlatform` constant and `true`. Exactly the same is happening in production. I assume, for now, that problem was in resolving promise returned from `process.exec` to early based on process 'exit' event when output streams are not flushed and closed. Stream issue addressed in PR #9654 and going to be included in next release.

IMO we should keep this issue opened for now and let @bodzebod verify it in next release with #9456 included.

``` javascript
const { default: child_process } = await import("node:child_process");
function run () {
    const p = child_process.spawn('powershell', [`[System.Console]::OutputEncoding = [Text.Encoding]::GetEncoding(850); (Get-WmiObject -Query "Select * from Win32_OptionalFeature where InstallState = \'1\'").Name  | select-string VirtualMachinePlatform`],{});
    let stdout = '';
    p.stdout.setEncoding('utf8');
    p.stdout.on('data', data => {
        stdout+=data;
    });
    p.on('close', code => {
        console.log(stdout.toString());
        console.log(stdout.toString().includes('VirtualMachinePlatform'));
    });
}
run();
```

**Comment by dgolovin** [comment]
@bodzebod latest podman release [here](https://podman-desktop.io/downloads) have a fix for this issue. Could you verify if it works for you now? If it is not, then there is one more fix in pipeline and should be included into the next release.

Thank you!

**Comment by vertgo** [comment]
Still having this issue with the latest build. 

<img width="866" alt="Image" src="https://github.com/user-attachments/assets/81d1e188-96e8-424d-8fc9-0564571754e0" />

**Comment by Straven** [comment]
Same issue 

![Image](https://github.com/user-attachments/assets/a35b6da1-12cd-45a7-a00a-d516631f5438)

**Comment by cdrage** [comment]
Re-opening this as there have been two users with the same issue (see above)

**Comment by Straven** [comment]
For me helps installing podman manually from https://github.com/containers/podman/releases, and then podman-desktop detects it.

**Comment by odockal** [comment]
@Straven That is definitely a workaround for the problem. Although, we still have the issue to solve.

**Comment by tux-86** [comment]
Same bug with Podman Desktop 1.21.0

**Comment by Kaliumhexacyanoferrat** [comment]
Have the same problem in a somewhat restricted enterprise environment. After encountering the error I installed podman manually which works well, but the UI still complains about the "Virtual Machine Platform" not being enabled (yet it is).

Specifying the podman executable path manually in the settings of the extension does not do the trick.
